### PR TITLE
Various Tweaks

### PR DESCRIPTION
**Pull request by kingthorin**
- CFP tab displaytext adjusted (speakers not papers)
- info.md adjusted, no point duplicating content.
- index.md dropped unused heading.

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping @BobNiko @cyberhelg

**Comment by kingthorin** [comment]
@julepka ?

**Comment by julepka** [comment]
Hi @kingthorin, we've received your PR and we'll review it soon.

**Comment by kingthorin** [comment]
If it makes you feel any better it was tested locally:
https://owasp.org/migration/#setup-a-local-testing-environment

I can get you a screenshot later if you like.

**Review by BobNiko — APPROVED** [review]

**Comment by BobNiko** [comment]
Hey, Rick! Thanks a lot for your attention to our chapter page!
We do appreciate your time spent on making it better =)

P.S. PR approved and merged!

Thanks again and have a great day!

-------------------
Regards,
Bohdan Nikitenko
Stuzo Security Engineer

**Comment by kingthorin** [comment]
Thanks, glad to help anywhere I can.

**Pull request merged**
